# _config.yml

title: Sreedevi Valeti
description: >- 
  Cloud Engineer | Devops Engineer

# Author info
author:
  name: Sreedevi Valeti
  email: sreedevivaleti16@gmail.com

# Theme
theme: jekyll-theme-slate

# Social Media links
social_links:
  github: "https://github.com/sreedevivaleti"
  linkedin: "https://linkedin.com/in/sreedevivaleti"

# Navigation settings
navbar:
  - text: "Home"
    url: "/"
  - text: "About"
    url: "/about"
  - text: "Contact"
    url: "/contact"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude some files/folders from being processed by Jekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Pagination settings (optional)
paginate: 5
paginate_path: "/page:num/"

# Site Locale (optional)
lang: en
